version: '3.9'

services:
  web:
    container_name: web
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${WEB_HTTP}:80
      - ${WEB_HTTPS}:443
    volumes:
      # - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./www/php74:/usr/share/nginx/html/php74
      - ./www/php81:/usr/share/nginx/html/php81
      # - ./www/php82:/usr/share/nginx/html/php82
    networks:
      - internal      
    depends_on:
      - mariadb
      - php74
      - php81
      # - php82

  php81:
    build:
      context: ./docker/php81/
      dockerfile: Dockerfile  
    networks:
      - internal
    volumes:
      - ./www/php81:/usr/share/nginx/html/php81
      - ./logs/php.log:/var/log/fpm-php81.www.log
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

  php74:
    build:
      context: ./docker/php74/
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - ./www/php74:/usr/share/nginx/html/php74
      - ./logs/php.log:/var/log/fpm-php74.www.log
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini      

  # Not working with Xdebug 3.2.0
  # php82:
  #   build:
  #     context: ./docker/php82/
  #     dockerfile: Dockerfile
  #   expose:
  #     - 9000      
  #   networks:
  #     - internal
  #   volumes:
  #     - ./www/php82:/usr/share/nginx/html/php82
  #     - ./logs/php.log:/var/log/fpm-php.www.log
  #     - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  #     - ./docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

  mariadb:
    image: mariadb:${MARIADB_VER}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mariadb/data:${MARIADB_DATA_DIR}
      # - ./logs:${MARIADB_LOG_DIR}
      # - ./docker/mariadb/conf:/etc/mysql
    ports:
      - ${DB_PORT}:3306

networks:
  internal:
    driver: bridge

