version: '3.9'

services:
  web:
    container_name: web
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${WEB_HTTP}:80
      - ${WEB_HTTPS}:443
    volumes:
      - ./docker/nginx/sites-available:/etc/nginx/sites-enabled
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./www:/opt/projects
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:${MARIADB_VER}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mariadb/data:${MARIADB_DATA_DIR}
#      - ./docker/mariadb/logs:${MARIADB_LOG_DIR}
#      - ./docker/mariadb/conf:/etc/mysql
    ports:
      - ${DB_PORT}:3306
