version: '3.9'

services:
  web:
    container_name: web
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    restart: always
    # environment:
    #   - NGINX_HOST=dev.sandbox.com
    #   - NGINX_PORT=80
    ports:
      - ${WEB_HTTP}:80
      - ${WEB_HTTPS}:443
    volumes:
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./www/php82:/usr/share/nginx/html/php82
      - ./www/php74:/usr/share/nginx/html/php74
    networks:
      - internal      
    depends_on:
      - mariadb
      - php74
      - php82

  php82:
    image: php:8.2.3-fpm-alpine
    networks:
      - internal
    volumes:
      - ./www/php82:/usr/share/nginx/html/php82
      - ./logs/php.log:/var/log/fpm-php.www.log

  php74:
    image: php:7.4-fpm-alpine
    networks:
      - internal
    volumes:
      - ./www/php74:/usr/share/nginx/html/php74
      - ./logs/php.log:/var/log/fpm-php.www.log

  mariadb:
    image: mariadb:${MARIADB_VER}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mariadb/data:${MARIADB_DATA_DIR}
      # - ./logs:${MARIADB_LOG_DIR}
      # - ./docker/mariadb/conf:/etc/mysql
    ports:
      - ${DB_PORT}:3306

networks:
  internal:
    driver: bridge

