FROM nginx:alpine
ADD ./default.conf /etc/nginx/conf.d

# RUN apt -y update
# RUN apt install -y nginx wget gnupg libxml2-dev libpng-dev curl libcurl4-gnutls-dev libxslt-dev libzip-dev libtidy-dev
# RUN wget -q https://packages.sury.org/php/apt.gpg -O- | apt-key add -
# RUN echo "deb https://packages.sury.org/php/ bullseye main" | tee /etc/apt/sources.list.d/php.list
# RUN apt -y install -y ca-certificates apt-transport-https
# RUN apt -y update && apt -y upgrade

# RUN apt install -y php7.4 php7.4-cli php7.4-common php7.4-opcache php7.4-curl php7.4-mbstring php7.4-mysql php7.4-zip php7.4-xml php7.4-fpm php7.4-bcmath

# RUN apt install -y php8.2 php8.2-cli php8.2-common php8.2-opcache php8.2-curl php8.2-mbstring php8.2-mysql php8.2-zip php8.2-xml php8.2-fpm php8.2-bcmath

# RUN curl -sS https://getcomposer.org/installer -o composer-setup.php
# RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer

#CMD ["apache2ctl", "-k", "graceful"]
#RUN kill -USR1 1